name: test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Build
        run: make build
      - name: Install
        run: make install
      - name: Check version
        run: reduce -v
      - name: Display help
        run: reduce -h
      - name: Generate URL
        run: reduce < test/test1 

  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Install latest
        run: go install github.com/TanmayPatil105/reduce@latest
      - name: Test
        run: reduce -h
