name: test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: make build
      - name: Check version
        run: ./reduce -v
      - name: Display help
        run: ./reduce -h
      - name: Generate URL
        run: ./reduce < test/test1